### ISSUE TITLE
闲话 Swift 协程（7）：GlobalActor 和异步函数的调度 | Bennyhuo

### ISSUE THREAD

**Issue by bennyhuo** [bennyhuo/Bennyhuo#74]
https://www.bennyhuo.com/2022/02/12/swift-coroutines-07-globalactor/ 

 我们已经知道可以使用 actor 来确保数据的线程安全，但对于数据的保护总是需要定义专门的 actor 实例是不是太麻烦了一些？

**Comment by jgh33** [comment]
请问，log方法是如何定义的呢，我想验证一下

**Comment by bennyhuo** [comment]
> 请问，log方法是如何定义的呢，我想验证一下

看下这里 https://github.com/bennyhuo/SwiftCoroutinesSample
